//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShareMVC6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int RouteID { get; set; }
        public string DepartingPoint { get; set; }
        public string ArrivingPoint { get; set; }
        public System.DateTime DepartingDate { get; set; }
        public System.TimeSpan DepartingTime { get; set; }
        public int FreeSpots { get; set; }
        public string Driver { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
    }
}
